template: |
  ## What’s Changed

  $CHANGES
tag-template: 'fds@$RESOLVED_VERSION'
tag-prefix: 'fds@'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch