on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      tag-new-versions:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - uses: salsify/action-detect-and-tag-new-version@v2
          with:
            tag-template: 'fds@{VERSION}'
